### ISSUE TITLE
Losing bits when parsing a Ulid

### ISSUE THREAD

**Issue by danny-cheung** [agilord/ulid#4]
```
import 'package:ulid/ulid.dart';

void main() {
  String orig = '01DQCTDTRP0000000000000000';

  u = Ulid.parse(orig);
  
  print(u.toString());
}
```
should output `01dqctdtrp0000000000000000`, but it outputs `0003ctdtrp0000000000000000`

**Comment by isoos** [comment]
On a console app on Dart 2.5, this prints `01dqctdtrp0000000000000000`. Are you running it on web or Flutter?

**Comment by danny-cheung** [comment]
Flutter

**Comment by isoos** [comment]
Published your fix, please verify if it is working.

**Comment by danny-cheung** [comment]
The fix works.
